# Generated by Django 5.0.6 on 2024-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sports', 'sports'), ('fighting', 'fighting'), ('action', 'action'), ('shooter', 'shooter'), ('battle royale', 'battle royale')], max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
